### GET category All
GET http://localhost:3000/api/categories
X-API-Key: SECRET
Accept: application/json

### POST create a new category
POST http://localhost:3000/api/categories
X-API-Key: SECRET
Accept: application/json
Content-Type: application/json

{
  "name": "Laberd"
}

### GET category by ID
GET http://localhost:3000/api/categories/4
X-API-Key: SECRET
Accept: application/json

### Update category by ID
PUT http://localhost:3000/api/categories/4
X-API-Key: SECRET
Accept: application/json
Content-Type: application/json

{
  "name": "Kikil"
}

### DELETE category by ID
DELETE http://localhost:3000/api/categories/4
X-API-Key: SECRET
Accept: application/json
